import json

lessons = [
    {"id":1,"title":"Posture & Alignment","course":"Technique","duration":"10 min","content":"NYVC: free voice needs free body. Stacked alignment. Your instrument is your body — align it for free, effortless sound.","practical":"Wall Drill: Back against wall, head/shoulders/hips touch. Step away maintaining posture. Sing a scale daily for 7 days."},
    {"id":2,"title":"Breath & Appoggio","course":"Technique","duration":"15 min","content":"Low breathing + solar plexus anchor. The engine behind every great voice. NYVC uses low breathing: belly expands, ribs open sideways.","practical":"Farinelli Cycle: Inhale 4, Hold 4, Exhale Ssss 8. Progress to 10-10-20."},
    {"id":3,"title":"Sustained Notes & Breath Control","course":"Technique","duration":"12 min","content":"Holding a single note steadily trains your appoggio. The goal is even tone from start to finish — no wavering, no breathiness.","practical":"Sustain a comfortable note for 20 seconds. Record and listen for wobble or breathiness."},
    {"id":4,"title":"Vocal Onset: Clean Note Starts","course":"Technique","duration":"10 min","content":"How you start a note determines everything. Glottal, aspirate, or balanced — learn the cleanest onset for singing.","practical":"Practice starting notes on a soft 'ah' — no hard glottal attack, no breathy escape. Aim for a clean, instant tone."},
    {"id":5,"title":"Vocal Health & Hydration","course":"Technique","duration":"8 min","content":"Your vocal folds need hydration, rest, and smart usage. Learn the habits that keep your voice healthy for life.","practical":"Track your water intake for 3 days. Note how your voice feels when hydrated vs. dehydrated."},
    {"id":6,"title":"The Daily Warm-Up Routine","course":"Technique","duration":"15 min","content":"A proper warm-up prepares your voice for singing. Lip trills, humming, and gentle sirens wake up your instrument safely.","practical":"Perform a 5-minute warm-up: 2 min lip trills, 2 min humming, 1 min gentle sirens. Sing before and after to feel the difference."},
    {"id":7,"title":"SOVT Exercises (Semi-Occluded Vocal Tract)","course":"Technique","duration":"12 min","content":"SOVT exercises like straw phonation and lip trills create back-pressure that helps your vocal folds vibrate efficiently.","practical":"Sing through a straw into water for 3 minutes. Then sing the same phrase without the straw — feel the ease."},
    {"id":8,"title":"Note Names & the Musical Alphabet","course":"Theory","duration":"10 min","content":"The 7 letters of the musical alphabet (A-G) are the foundation of all Western music. Learn to name any note on your instrument.","practical":"Say the note names of the C major scale ascending and descending. Do this daily until it is instant."},
    {"id":9,"title":"The Major Scale","course":"Theory","duration":"12 min","content":"The major scale is the mother of all scales. Its pattern of whole steps and half steps (W-W-H-W-W-W-H) creates the bright, happy sound we know.","practical":"Sing a major scale starting on 3 different notes. Use a piano app to check your accuracy."},
    {"id":10,"title":"Intervals: Unison & Octave","course":"Theory","duration":"10 min","content":"An interval is the distance between two notes. Unison (same note) and octave (same note, higher/lower) are the most fundamental.","practical":"Play a note on a piano app. Sing the same note, then the octave above. Record and check."},
    {"id":11,"title":"Time Signatures & Meter","course":"Theory","duration":"12 min","content":"Time signatures tell you how many beats are in each measure and what note gets the beat. 4/4, 3/4, 6/8 — each creates a different feel.","practical":"Clap along to 3 songs in different time signatures. Count aloud: 1-2-3-4 for 4/4, 1-2-3 for 3/4."},
    {"id":12,"title":"Rhythm & Note Values","course":"Theory","duration":"15 min","content":"Whole notes, half notes, quarter notes, eighth notes — each has a specific duration. Reading rhythm is like reading a language.","practical":"Clap and count a rhythm pattern: quarter-quarter-half. Then sing it on a single note."},
    {"id":13,"title":"Ear Training: Call & Response","course":"Ear Training","duration":"12 min","content":"Call and response trains your ear and your musical memory. Hear a phrase, sing it back. This is how musicians learn by ear.","practical":"Have a friend play 3-note phrases. Sing them back accurately. Start simple, increase complexity."},
    {"id":14,"title":"Pitch Drift & Intonation Awareness","course":"Ear Training","duration":"10 min","content":"Pitch drift is when you slowly go flat or sharp without realizing. Developing intonation awareness keeps you locked on pitch.","practical":"Sing along with a drone note. Record yourself. Listen back for moments where you drift off pitch."},
    {"id":15,"title":"Microphone Technique Fundamentals","course":"Performance","duration":"10 min","content":"How you use a microphone affects your tone, volume, and stage presence. Proximity effect, angle, and distance — master these.","practical":"Practice singing into a mic (or pretend mic). Try 1 inch, 6 inches, and 12 inches away. Hear the difference in tone."},
    {"id":16,"title":"Overcoming Stage Fright","course":"Performance","duration":"12 min","content":"Stage fright is normal — even pros get it. The key is channeling that energy into your performance instead of letting it paralyze you.","practical":"Record a video of yourself singing. Watch it back. Do this 3 times in one week and note your comfort level increasing."},
    {"id":17,"title":"Song Structure: Verse, Chorus, Bridge","course":"Theory","duration":"10 min","content":"Most popular songs follow predictable structures. Understanding verse-chorus-bridge helps you learn songs faster and perform them better.","practical":"Pick a song you know. Map out its structure: where is the verse, chorus, bridge, intro, outro?"},
    {"id":18,"title":"The Discipline of Daily Practice","course":"Mindset","duration":"8 min","content":"Talent gets you nowhere without discipline. A daily practice habit — even 15 minutes — transforms your voice faster than occasional long sessions.","practical":"Set a daily 15-minute practice alarm. Do it for 14 days straight. Track your streak."},
    {"id":19,"title":"SOVT Advanced: Straw Phonation","course":"Technique","duration":"15 min","content":"Advanced straw phonation exercises target specific vocal challenges — range extension, register blending, and breath efficiency.","practical":"Use a straw to sing arpeggios across your entire range. Notice how the back-pressure helps in your passaggio."},
    {"id":20,"title":"Chest Voice: Your Power Register","course":"Technique","duration":"12 min","content":"Chest voice is your lower, powerful register. It is where your speaking voice lives and where most pop/soul singing happens.","practical":"Sing a comfortable descending scale on 'ah' — feel the vibration in your chest. Go as low as is comfortable."},
    {"id":21,"title":"Head Voice: Your Upper Register","course":"Technique","duration":"12 min","content":"Head voice is your lighter, upper register. It feels like the sound resonates in your head rather than your chest.","practical":"Siren from your chest voice up into head voice on 'oo'. Feel the shift in resonance from chest to head."},
    {"id":22,"title":"Mixed Voice: Blending Registers","course":"Technique","duration":"15 min","content":"Mixed voice blends chest and head voice so you can sing powerfully through your entire range without breaking.","practical":"Sing a scale from low to high on 'ng'. Keep the same light coordination as you ascend."},
    {"id":23,"title":"Vowel Modification (Vowel Migration)","course":"Technique","duration":"12 min","content":"As you sing higher, vowels need to modify (close) to maintain resonance and avoid strain. 'Ah' becomes 'uh', 'ee' becomes 'ih'.","practical":"Sing a 5-tone scale on 'ah' ascending. Notice when you need to slightly close the vowel to keep it strain-free."},
    {"id":24,"title":"Resonance & Placement","course":"Technique","duration":"12 min","content":"Resonance is where your sound vibrates. Forward placement (mask/nasal) cuts through a mix; back placement creates warmth.","practical":"Hum and feel the buzz in your lips/nose (mask). Then sing 'ah' and try to maintain that same forward sensation."},
    {"id":25,"title":"Nasality: When It Helps, When It Hurts","course":"Technique","duration":"10 min","content":"A little nasal resonance adds brightness and cuts through a mix. Too much sounds pinched. Learn to control it.","practical":"Pinch your nose and sing. If the tone changes drastically, you are too nasal. Practice reducing nasal pull."},
    {"id":26,"title":"Vibrato: Natural Oscillation","course":"Technique","duration":"10 min","content":"Vibrato is a natural pitch oscillation that happens when your voice is free and well-supported. Forced vibrato sounds fake.","practical":"Sustain a comfortable note with good support. Do not try to create vibrato — let it happen naturally. Record and listen."},
    {"id":27,"title":"Articulation: Consonants & Diction","course":"Technique","duration":"10 min","content":"Clear diction makes your singing intelligible. Consonants (T, K, D, B) need to be crisp without disrupting the airflow.","practical":"Sing a phrase focusing on clear consonants. Record and ask a friend: can you understand every word?"},
    {"id":28,"title":"Intervals: 2nds & 3rds","course":"Theory","duration":"12 min","content":"Seconds (adjacent notes) and thirds (every other note) are the building blocks of melody and harmony.","practical":"Play a note, then sing a major 3rd above. Check with a piano. Repeat for minor 3rd."},
    {"id":29,"title":"Triads: Major, Minor, Diminished","course":"Theory","duration":"15 min","content":"A triad is 3 notes stacked in thirds. Major (bright), minor (dark), diminished (tense) — these are the building blocks of chords.","practical":"Sing a C major triad (C-E-G) ascending and descending. Then try C minor (C-Eb-G). Hear the difference."},
    {"id":30,"title":"Rhythm: 16th Notes & Syncopation","course":"Theory","duration":"15 min","content":"Sixteenth notes divide the beat into 4 parts. Syncopation puts emphasis on unexpected beats — the heart of groove.","practical":"Clap a syncopated pattern: 1-ee-and-uh-2-ee-and-uh. Use a metronome at 60 BPM."},
    {"id":31,"title":"Circle of Fifths","course":"Theory","duration":"15 min","content":"The Circle of Fifths shows the relationship between all 12 keys. It is the master map of music theory.","practical":"Draw the Circle of Fifths from memory. Start at C and go clockwise: C-G-D-A-E-B-F#-Db-Ab-Eb-Bb-F."},
    {"id":32,"title":"Chord Quality Recognition by Ear","course":"Ear Training","duration":"12 min","content":"Train your ear to instantly recognize major, minor, diminished, and augmented chords. This skill makes you a better singer and musician.","practical":"Have a friend play random chords. Identify if they are major or minor. Aim for 80% accuracy."},
    {"id":33,"title":"Harmonic Listening: Hearing the Chords","course":"Ear Training","duration":"15 min","content":"When you can hear the chord changes in a song, you can anticipate melody and harmony. This is how pros learn songs instantly.","practical":"Play a I-V-vi-IV progression. Sing along with each chord change. Try to hear when the chord shifts."},
    {"id":34,"title":"Stage Presence & Body Language","course":"Performance","duration":"12 min","content":"Your body speaks as loudly as your voice. Confident posture, intentional movement, and eye contact make your performance memorable.","practical":"Record a full performance video. Watch it muted — does your body language convey confidence and emotion?"},
    {"id":35,"title":"Emotional Connection to Lyrics","course":"Performance","duration":"10 min","content":"Singing notes is easy. Singing with genuine emotion is what moves people. Connect every lyric to a real feeling or memory.","practical":"Pick a song. Before singing each line, ask: 'When have I felt this way?' Sing from that place."},
    {"id":36,"title":"Worship Leading: Shepherding a Room","course":"Performance","duration":"15 min","content":"Worship leading is about serving the room, not performing. It requires sensitivity, spontaneity, and deep musical knowledge.","practical":"Practice leading a 3-song set with smooth transitions. Record it and evaluate your flow and sensitivity."},
    {"id":37,"title":"Afrobeats Vocal Style","course":"Style-Specific","duration":"15 min","content":"Afrobeats vocals are rhythmic, percussive, and groove-driven. Pitch bends, call-and-response, and syncopation define the style.","practical":"Listen to a Burna Boy or Wizkid track. Mimic the vocal rhythm and pitch bends. Record your version."},
    {"id":38,"title":"Praise & Worship Vocal Delivery","course":"Style-Specific","duration":"12 min","content":"Praise and worship vocals range from intimate and tender to powerful and anointed. Dynamic control is essential.","practical":"Sing the same worship chorus in 3 dynamics: whisper-soft, conversational, and full praise. Feel the emotional shift."},
    {"id":39,"title":"Building Your Personal Brand","course":"Business","duration":"12 min","content":"Your brand is what people say about you when you are not in the room. Define your unique voice, look, and message.","practical":"Write a 3-sentence artist statement: Who are you as an artist? What makes you different?"},
    {"id":40,"title":"Advanced SOVT: Pressure Exercises","course":"Technique","duration":"15 min","content":"Advanced semi-occluded vocal tract exercises target specific technical challenges — high range, power, and register transitions.","practical":"Use a straw to sing arpeggios across your full range. Notice how the back-pressure supports your passaggio."},
    {"id":41,"title":"Belting: Power Without Pain","course":"Technique","duration":"15 min","content":"Belting is powerful high singing done safely. It requires strong appoggio, twang, and vowel modification — never throat pushing.","practical":"Belt a comfortable high note on 'eh'. Feel the engagement in your body, not your throat."},
    {"id":42,"title":"Pharyngeal Voice (Twang)","course":"Technique","duration":"12 min","content":"Pharyngeal voice narrows the space above the larynx, creating a bright, cutting tone. Essential for belting and cutting through a mix.","practical":"Imitate a cat meow — feel the bright, narrow sensation. Apply that same brightness to an open 'ah' vowel."},
    {"id":43,"title":"Vocal Agility: Scales & Arpeggios","course":"Technique","duration":"15 min","content":"Agility is the ability to move quickly and accurately between notes. Fast scales and arpeggios build this skill.","practical":"Sing a major scale on 'ee' at 80 BPM. Increase tempo by 5 BPM each day."},
    {"id":44,"title":"Registration: Understanding Your Passaggio","course":"Technique","duration":"12 min","content":"Your passaggio is the transition zone between registers. Knowing where it is helps you blend smoothly instead of breaking.","practical":"Sing a slow siren from low to high. Note where the shift happens. Practice smoothing it."},
    {"id":45,"title":"Messa di Voce: Dynamic Control","course":"Technique","duration":"12 min","content":"Messa di voce means 'placing the voice' — singing one note from soft to loud and back. It builds incredible breath control.","practical":"Sustain a comfortable note. Start pianissimo, grow to forte, then back to pianissimo. One breath."},
    {"id":46,"title":"Riffs & Runs: Melismatic Singing","course":"Technique","duration":"15 min","content":"Riffs and runs are fast, decorative note sequences. They require agility, accuracy, and breath support — not just speed.","practical":"Learn a simple 5-note riff slowly with a metronome. Gradually increase speed while maintaining accuracy."},
    {"id":47,"title":"Minor Scales: Natural, Harmonic, Melodic","course":"Theory","duration":"15 min","content":"Minor scales have a darker, sadder quality. Natural minor, harmonic minor, and melodic minor each have unique sounds.","practical":"Sing a natural minor scale. Then sing a harmonic minor (raised 7th). Hear the different tension."},
    {"id":48,"title":"7th Chords: Maj7, min7, Dom7","course":"Theory","duration":"15 min","content":"7th chords add a 4th note to a triad, creating richer harmony. Major 7 (dreamy), minor 7 (jazzy), dominant 7 (tense).","practical":"Play a Cmaj7 chord. Sing each note: C-E-G-B. Then try C7 (C-E-G-Bb). Hear the difference."},
    {"id":49,"title":"Compound Time: 6/8, 9/8, 12/8","course":"Theory","duration":"12 min","content":"Compound time divides beats into groups of 3. 6/8 feels like 2 big beats (each divided into 3). Common in gospel and ballads.","practical":"Clap along to a 6/8 song. Count: 1-2-3-4-5-6 with emphasis on 1 and 4. Feel the rolling groove."},
    {"id":50,"title":"Modulation: Changing Keys Mid-Song","course":"Theory","duration":"12 min","content":"Modulation is shifting to a new key within a song. It creates excitement and emotional lift — common in gospel final choruses.","practical":"Find a song that modulates. Identify exactly where it happens and what the new key is."},
    {"id":51,"title":"Intervals: 4ths, 5ths & 6ths","course":"Theory","duration":"15 min","content":"Perfect 4ths and 5ths are the most consonant intervals. 6ths are the foundation of harmony singing.","practical":"Play a note, sing a perfect 5th above. Check accuracy. Repeat for 4th and 6th."},
    {"id":52,"title":"Transcription: Writing Down What You Hear","course":"Ear Training","duration":"15 min","content":"Transcription is writing out a melody or chord progression by ear. It is one of the most powerful ear training exercises.","practical":"Pick a simple 4-bar melody. Figure out the notes and write them down. Check with a piano."},
    {"id":53,"title":"Relative Pitch Development","course":"Ear Training","duration":"15 min","content":"Relative pitch is the ability to identify intervals and notes in relation to a reference. It is trainable and essential for singers.","practical":"Play a reference note. Then play a random note. Identify the interval. Do this for 10 minutes daily."},
    {"id":54,"title":"In-Ear Monitors: Live Performance Setup","course":"Performance","duration":"12 min","content":"In-ear monitors (IEMs) give you a personal mix on stage. Proper setup protects your hearing and improves your performance.","practical":"If you have IEMs, set up a mix with your voice slightly louder than the band. Practice singing with them."},
    {"id":55,"title":"Visual Storytelling in Performance","course":"Performance","duration":"12 min","content":"Your face and body tell the story of the song. Every expression should be intentional and connected to the lyrics.","practical":"Record a close-up video of yourself singing. Watch muted — do your expressions match the emotion of the lyrics?"},
    {"id":56,"title":"Setlist Design: Crafting a Journey","course":"Performance","duration":"12 min","content":"A great setlist takes the audience on a journey. Energy, key, tempo, and emotional arc all matter.","practical":"Design a 5-song setlist. Map the energy curve: where is the peak? Where is the rest?"},
    {"id":57,"title":"R&B Vocal Styling: Runs & Soul","course":"Style-Specific","duration":"15 min","content":"R&B vocals are smooth, soulful, and melismatic. Runs, bends, and emotional delivery define the genre.","practical":"Listen to a Beyonce or H.E.R. track. Mimic a 10-second phrase, matching every run and bend exactly."},
    {"id":58,"title":"Gospel Vocal Techniques","course":"Style-Specific","duration":"15 min","content":"Gospel vocals are powerful, emotional, and technically demanding. Growls, shouts, runs, and dynamic extremes are hallmarks.","practical":"Practice a gospel run: start on a note, descend 5 notes quickly with precision."},
    {"id":59,"title":"Building a Digital Portfolio","course":"Business","duration":"12 min","content":"Your digital portfolio is your online resume. Best recordings, photos, bio, and press — all in one place.","practical":"Choose your 3 best recordings. Write a 1-page bio. Create a simple portfolio page or Linktree."},
    {"id":60,"title":"Advanced Melisma: Complex Runs","course":"Technique","duration":"15 min","content":"Advanced melisma involves multi-octave runs with precise pitch control. Speed comes from accuracy first.","practical":"Learn a complex run from a pro singer. Break it into 3-note chunks. Master each chunk, then connect them."},
    {"id":61,"title":"Vocal Distortion: Grit & Rasp Safely","course":"Technique","duration":"12 min","content":"Vocal distortion (grit/rasp) adds edge to your sound. Done correctly, it is safe. Done wrong, it damages your voice.","practical":"Practice a light growl on a comfortable note. Add just enough texture without pain. Stop if it hurts."},
    {"id":62,"title":"Whistle Register","course":"Technique","duration":"10 min","content":"Whistle register is the highest female register — piercing and flute-like. Not everyone accesses it, but it can be developed.","practical":"Try imitating a whistle on a high 'oo'. Slide up gently. Do not push."},
    {"id":63,"title":"Vocal Stamina & Endurance","course":"Technique","duration":"12 min","content":"Singing for a full set without fatigue requires stamina. Build it gradually with consistent practice and proper technique.","practical":"Sing a full 20-minute set. Note when your voice tires. Extend by 2 minutes each week."},
    {"id":64,"title":"Acoustic Tuning: Singing in Tune with Instruments","course":"Ear Training","duration":"12 min","content":"Singing in tune with a piano, guitar, or band requires constant micro-adjustments. Your ear must be faster than your voice.","practical":"Play a chord on piano. Sing each note of the chord in tune. Listen for the lock when you are perfectly centered."},
    {"id":65,"title":"Dynamic Tapering: Ending Songs with Control","course":"Technique","duration":"10 min","content":"How you end a song matters as much as how you start. A controlled, emotional ending leaves a lasting impression.","practical":"Practice ending a song on a long, fading note. Start mezzo-forte, taper to pianissimo. Keep the pitch steady."},
    {"id":66,"title":"Vocal Rehabilitation: Recovering from Strain","course":"Technique","duration":"15 min","content":"If you have strained your voice, recovery requires rest, gentle exercises, and patience. Never push through pain.","practical":"Do 10 minutes of gentle humming and lip trills. If your voice feels tired, stop. Rest is part of training."},
    {"id":67,"title":"Modal Concepts: Mixolydian, Dorian, Phrygian","course":"Theory","duration":"15 min","content":"Modes are variations of the major scale that create different moods. Mixolydian (bluesy), Dorian (jazzy), Phrygian (dark).","practical":"Play a C mixolydian scale. Sing it. Hear how the flat 7th gives it a bluesy feel."},
    {"id":68,"title":"Polyrhythms & African Rhythmic Concepts","course":"Theory","duration":"15 min","content":"Polyrhythms layer different rhythms simultaneously. African music is built on these complex, interlocking patterns.","practical":"Clap a 3-against-2 pattern: one hand claps 2 beats, the other claps 3 beats in the same time."},
    {"id":69,"title":"Extended Chords: 9ths, 11ths, 13ths","course":"Theory","duration":"15 min","content":"Extended chords add color and sophistication. 9ths, 11ths, and 13ths are common in jazz, neo-soul, and gospel.","practical":"Play a Cmaj9 chord. Sing each note: C-E-G-B-D. Hear how the 9th adds a dreamy quality."},
    {"id":70,"title":"Microtonal Singing: Blue Notes & Pitch Bends","course":"Technique","duration":"12 min","content":"Microtonal singing uses notes between the piano keys. Blue notes, pitch bends, and scoops are essential in blues, gospel, and African music.","practical":"Sing a note, then bend down a quarter-tone (blue note). Practice scooping up to notes from below."},
    {"id":71,"title":"Advanced Modulation: Modulation Types","course":"Theory","duration":"12 min","content":"Different modulation types (pivot chord, direct, chromatic) create different emotional effects. Pros choose intentionally.","practical":"Find 3 songs with key changes. Identify the modulation type: pivot chord or direct shift?"},
    {"id":72,"title":"Aural Polyphony: Hearing Multiple Lines","course":"Ear Training","duration":"15 min","content":"Aural polyphony is hearing multiple musical lines simultaneously — melody, harmony, bass. It is advanced ear training.","practical":"Listen to a 3-part harmony. Focus on one part at a time. Then try to hear all 3 simultaneously."},
    {"id":73,"title":"Chord Progression Dictation","course":"Ear Training","duration":"15 min","content":"Charting a live band's chord progression by ear is a master-level skill. Identify bass movement and chord qualities.","practical":"Listen to a new song. Write the chord progression using Roman numerals. Sing the roots to check."},
    {"id":74,"title":"Microphone Artistry: Condenser vs Dynamic","course":"Performance","duration":"12 min","content":"Studio condensers capture every nuance; live dynamics handle high volumes. Understanding both makes you versatile.","practical":"Record the same phrase on different mics. Compare the tone and adjust your distance."},
    {"id":75,"title":"Camera Artistry: Live-Stream & TV Performance","course":"Performance","duration":"12 min","content":"On camera, every expression is amplified. Subtle, controlled performance reads better than broad stage movements.","practical":"Record a close-up performance video. Watch muted — do your eyes and face tell the story?"},
    {"id":76,"title":"Spontaneous Flow: Prophetic Song Leading","course":"Performance","duration":"15 min","content":"Leading spontaneous worship requires technical control, sharp listening, and the confidence to follow the room's energy.","practical":"Loop a 2-chord progression. Ad-lib melody and lyrics for 5 minutes straight. Build a clear story arc."},
    {"id":77,"title":"Audience Engagement Psychology","course":"Performance","duration":"12 min","content":"Great performance is a two-way conversation. Read the room, break barriers with call-and-response, and invite participation.","practical":"Design a 2-minute interactive segment with call-and-response before the final chorus."},
    {"id":78,"title":"Vocal Arranging for Ensembles (SATB)","course":"Performance","duration":"15 min","content":"Vocal arranging spreads chords across Soprano, Alto, Tenor, Bass. Voice-leading and comfortable voicings are key.","practical":"Write a 3-part harmony arrangement for a 4-bar melody. Record yourself singing all 3 parts."},
    {"id":79,"title":"Hybrid Styling: Classical Tone Meets CCM Belt","course":"Style-Specific","duration":"15 min","content":"Modern music often requires blending classical richness with commercial belt power. Cross-genre coordination is essential.","practical":"Sing a phrase with operatic classical tone. On the next phrase, transition into a bright commercial belt."},
    {"id":80,"title":"Neo-Soul Styling: Microtonal Drifts & Lazy Phrasing","course":"Style-Specific","duration":"15 min","content":"Neo-soul vocals use 'lazy time' — singing behind the beat — and microtonal pitch drifts for emotional effect.","practical":"Loop a neo-soul groove. Sing a melody, deliberately delaying phrases by an eighth note."},
    {"id":81,"title":"Cinematic & Theatrical Belting","course":"Style-Specific","duration":"15 min","content":"Epic pop and musical theatre belting requires sustained dramatic delivery with stable larynx and wide acoustic space.","practical":"Sing a dramatic high belt on a modified open vowel. Hold for 8 counts without vibrato wobble."},
    {"id":82,"title":"Vocal Healing: Somatic Pedagogy","course":"Technique","duration":"12 min","content":"The voice mirrors the nervous system. Emotional trauma locks the body. Low-frequency toning stimulates the vagus nerve.","practical":"Close your eyes. Spend 5 minutes vocalizing a low 'OM' or 'AH'. Send vibration into your chest."},
    {"id":83,"title":"Vocal Psychodynamics: Overcoming Passaggio Fear","course":"Technique","duration":"12 min","content":"Fear of high notes causes laryngeal constriction. Reframing the upper range as ease rewires your neuromuscular response.","practical":"Before a difficult high phrase, speak it in a goofy cartoon voice. Transition that same coordination into singing."},
    {"id":84,"title":"Anatomy of the Voice: Advanced Laryngeal Physiology","course":"Technique","duration":"15 min","content":"The larynx has cartilages (thyroid, cricoid, arytenoid) and muscles. Understanding thyroarytenoid vs cricothyroid empowers targeted practice.","practical":"Study a 3D larynx diagram. Label the thyroid cartilage, cricoid, and vocal ligaments."},
    {"id":85,"title":"Acoustics & Formants: The Science of Resonance","course":"Technique","duration":"15 min","content":"Sound starts at the vocal folds (source) and is filtered by the vocal tract (filter). Formants (F1, F2) are acoustic peaks you can tune.","practical":"Sing a sustained 'EE', then slowly drop jaw to 'AH' keeping pitch identical. Use an analyzer app."},
    {"id":86,"title":"Aerodynamics: Subglottic Pressure vs Glottal Resistance","course":"Technique","duration":"12 min","content":"Healthy singing balances air pressure below the folds with muscular resistance keeping them together.","practical":"Sing a 5-tone scale using puffed-cheek blowfish technique. Feel the pressure balance."},
    {"id":87,"title":"Contract Law: Splitting Royalties","course":"Business","duration":"12 min","content":"Protect your intellectual property. Establish clear agreements on master rights, publishing splits, and mechanical royalties.","practical":"Draft a 1-page split sheet template with creator names, signatures, date, and ownership percentages."},
    {"id":88,"title":"Studio Business: Session Vocalist Workflow","course":"Business","duration":"12 min","content":"Top session vocalists are fast and professional. Memorize lyrics, understand audio terms, and deliver clean harmonies on take one.","practical":"Record a lead vocal, then 3 harmony tracks. Focus on identical cutoffs and timing."},
    {"id":89,"title":"Structuring High-End Coaching Programs","course":"Business","duration":"15 min","content":"Premium coaching programs bundle custom curricula, vocal tracking reviews, and branding mentorship.","practical":"Design a 12-week vocal coaching package with transformation goal and premium pricing."},
    {"id":90,"title":"Digital Distribution & Independent Monetization","course":"Business","duration":"12 min","content":"Use digital distributors, fan-funding platforms, vocal sample packs, and sync licensing for multiple revenue streams.","practical":"Research a sync licensing platform. Outline a submission strategy for 3 original tracks."},
    {"id":91,"title":"Advanced Studio Tech: Vocal Production & Mixing","course":"Business","duration":"15 min","content":"Vocalists who produce their own voice have an edge. EQ, compression, and pitch correction create radio-ready stems.","practical":"Take a raw vocal. Apply high-pass filter, compressor (4:1), and de-esser. Export the clean track."},
    {"id":92,"title":"Sustainable Artist Ecosystem: Longevity Strategy","course":"Business","duration":"12 min","content":"A lifelong career requires balancing performance with rest and diversification. Digital assets keep you profitable during vocal rest.","practical":"Map a 3-year career strategy with rest blocks and a digital asset launch."},
    {"id":93,"title":"Vocal Pedagogy: The Art of Diagnosis","course":"Technique","duration":"15 min","content":"A great coach diagnoses by ear — structural, aerodynamic, or register-based — and provides the exact exercise to fix it.","practical":"Listen to an amateur singer. Write a 3-point diagnosis: bottleneck, cause, and 2 targeted drills."},
    {"id":94,"title":"Designing Custom Curricula for Diverse Students","course":"Technique","duration":"15 min","content":"Every student has unique goals. A master coach designs custom technical maps for each individual.","practical":"Create two 4-week lesson plans: one for an Afrobeats artist, one for an acoustic singer-songwriter."},
    {"id":95,"title":"Ethics in Vocal Coaching","course":"Mindset","duration":"12 min","content":"The voice is tied to identity. Coaches must create safe spaces, respect boundaries, and support authentic journeys.","practical":"Write a 1-page coaching philosophy with boundaries and feedback delivery approach."},
    {"id":96,"title":"Masterclass Blueprint: Teaching Groups Effectively","course":"Technique","duration":"12 min","content":"Group teaching requires universal concepts that apply to everyone while engaging individual volunteers.","practical":"Draft a 60-minute masterclass outline with warm-up, lecture, hot-seat coaching, and Q&A blocks."},
    {"id":97,"title":"Advanced Lesson Management & Client Tracking","course":"Business","duration":"12 min","content":"Long-term retention requires organized progress tracking. Log audio benchmarks, assign homework, and celebrate milestones.","practical":"Build a student tracking database template with goals, lesson date, focus, exercises, and recordings."},
    {"id":98,"title":"Capstone Project: Selecting Your Masterpiece Track","course":"Performance","duration":"15 min","content":"The capstone project is your ultimate test. Choose a track that demands everything — technique, theory, emotion, and style.","practical":"Select your capstone song. Write a structural analysis: key, registers, vowel modifications."},
    {"id":99,"title":"The Final Capstone Performance","course":"Performance","duration":"20 min","content":"Lesson 100 is the peak — integration of vocal science, theory, performance, style, and business mindset.","practical":"Record your final capstone performance. Self-evaluate: technical accuracy, emotional delivery, and polish."},
    {"id":100,"title":"Graduation & Beyond: Your Artist Roadmap","course":"Business","duration":"15 min","content":"You have completed 100 lessons. Now build your future: continued practice, community, coaching, and career strategy.","practical":"Write your 1-year artist development plan with practice schedule, performance goals, and income targets."}
]

# Generate JS
lines = ['  lessons: [']
for l in lessons:
    title = l['title'].replace("'", "\\'")
    course = l['course'].replace("'", "\\'")
    content = l['content'].replace("'", "\\'").replace('\n', '\\n')
    practical = l['practical'].replace("'", "\\'").replace('\n', '\\n')
    
    lines.append(f"    {{ id:{l['id']}, title:'{title}', course:'{course}', duration:'{l['duration']}', content:'{content}',")
    lines.append(f"      steps:[")
    lines.append(f"        {{type:'teach',title:'{title}',body:'{content}'}},")
    lines.append(f"        {{type:'practice',title:'Practical Assignment',body:'{practical}'}}")
    lines.append(f"      ]}},")

lines.append('  ],')

with open('/data/data/com.termux/files/home/sessionswithtoby-/new_lessons_block.txt', 'w') as f:
    f.write('\n'.join(lines))

print(f"Generated {len(lessons)} lessons, {len(lines)} lines")
